# The URL the site will be built for
base_url = "https://3721.netlify.app"
theme = "neovim-theme"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[extra]

# set the name of the blog
blog_name = "yinbingshi"
background_image = "/assets/background.jpg"
